// Problem 2
// =========
// 
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 
//                   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// Find the sum of all the even-valued terms in the sequence which do not
// exceed four million.

var n1 = 1;
var n2 = 0;
var total = 0;
var fib;

do {
	if((fib = n1 + n2) % 2 == 0) {
		total += fib;
	}
	n1 = n2;
	n2 = fib;
} while(fib < 4000000);

// TODO: return your answer for this prompt.
return total;
