// Problem 2
// =========
// 
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 
//                   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// Find the sum of all the even-valued terms in the sequence which do not
// exceed four million.

// Fibonacci sequence as a generator
function* fib(limit) {
    for (let prev = 0, cur = 1; cur < limit; [prev, cur] = [cur, prev + cur]) {
        yield cur;
    }
}

return[...fib(4000000)]               // terms in the sequence which do not exceed four million
            .filter(i => i % 2 == 0)  // even-valued terms
            .reduce((j, k) => j + k); // sum of all the even-valued terms
