// Problem 44
// ==========
// 
// Pentagonal numbers are generated by the formula, P[n]=n(3n-1)/2. The first
// ten pentagonal numbers are:
// 
//                1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
// 
// It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
// difference, 70 - 22 = 48, is not pentagonal.
// 
// Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
// and difference is pentagonal and D = |P[k] - P[j]| is minimised; what is
// the value of D?

function isPentagonal(n) {
	return Number.isInteger((1 + Math.sqrt(24 * n + 1)) / 6);
}

var pentagons = [1];

for(var n = 2; n < 10000; n++) {
	var p = n * (3 * n - 1) / 2;
	for(var i in pentagons) {
		if(isPentagonal(pentagons[i] + p) && isPentagonal(p - pentagons[i])) {
			return p - pentagons[i];
		}
	}
	pentagons.push(p);
}

return 0;
